# Generated by Django 5.1.5 on 2025-02-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivery",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
